module.exports = [
    {name: "Lionel Messi", country: "Argentina", number: 10, position: "Forward", photo: "/public/photos/Messi.JPG"},
    {name: "Cristiano Ronaldo", country: "Portugal", number: 7, position: "Forward" , photo: "/public/photos/Ronaldo.JPG"},
    {name: "Neymar Jr", country: "Brazil", number: 10, position: "Forward" , photo: "/public/photos/Neymar.JPG"},
    {name: "Robert Lewandowski", country: "Poland", number: 9, position: "Forward" , photo: "/public/photos/Lewa.JPG"},
    {name: "Kevin De Bruyne", country: "Belgium", number: 17, position: "Midfielder" , photo: "/public/photos/kdb.JPG"},
    {name: "Virgil van Dijk", country: "Netherlands", number: 4, position: "Defender" , photo: "/public/photos/Virgil.JPG"},
    {name: "Kylian Mbappé", country: "France", number: 7, position: "Forward" , photo: "/public/photos/Mbappe.JPG"},
    {name: "Sergio Ramos", country: "Spain", number: 4, position: "Defender" , photo: "/public/photos/Ramos.JPG"},
    {name: "Mohamed Salah", country: "Egypt", number: 11, position: "Forward" , photo: "/public/photos/Salah.JPG"},
    {name: "Alisson Becker", country: "Brazil", number: 1, position: "Goalkeeper" , photo: "/public/photos/Alisson.JPG"},
    {name: "Harry Kane", country: "England", number: 9, position: "Forward" , photo: "/public/photos/Kane.JPG"},
    {name: "Eden Hazard", country: "Belgium", number: 7, position: "Forward" , photo: "/public/photos/Hazard.JPG"},
    {name: "Luka Modric", country: "Croatia", number: 10, position: "Midfielder" , photo: "/public/photos/Modric.JPG"},
    {name: "Sadio Mane", country: "Senegal", number: 10, position: "Forward" , photo: "/public/photos/Mane.JPG"},
    {name: "Bruno Fernandes", country: "Portugal", number: 18, position: "Midfielder" , photo: "/public/photos/Bruno.JPG"},
    {name: "Joshua Kimmich", country: "Germany", number: 6, position: "Midfielder" , photo: "/public/photos/Kimmich.JPG"},
    {name: "Riyad Mahrez", country: "Algeria", number: 26, position: "Forward" , photo: "/public/photos/Mahrez.JPG"},
    {name: "Trent Alexander-Arnold", country: "England", number: 66, position: "Defender" , photo: "/public/photos/Trent.JPG"},
    {name: "Gianluigi Donnarumma", country: "Italy", number: 99, position: "Goalkeeper" , photo: "/public/photos/Dona.JPG"},
    {name: "Fabinho", country: "Brazil", number: 3, position: "Midfielder" , photo: "/public/photos/Fabinho.JPG"},
    {name: "Jan Oblak", country: "Slovenia", number: 13, position: "Goalkeeper" , photo: "/public/photos/Oblak.JPG"},
    {name: "Raheem Sterling", country: "England", number: 7, position: "Forward" , photo: "/public/photos/Raheem.JPG"},
    {name: "Paul Pogba", country: "France", number: 6, position: "Midfielder" , photo: "/public/photos/Pogba.JPG"},
    {name: "Marquinhos", country: "Brazil", number: 5, position: "Defender" , photo: "/public/photos/Marquinhos.JPG"},
    {name: "Gareth Bale", country: "Wales", number: 11, position: "Forward" , photo: "/public/photos/Bale.JPG"},
    {name: "Thiago Alcantara", country: "Spain", number: 6, position: "Midfielder" , photo: "/public/photos/Thiago.JPG"},
    {name: "Hakim Ziyech", country: "Morocco", number: 22, position: "Midfielder" , photo: "/public/photos/Ziyech.JPG"},
    {name: "Frenkie de Jong", country: "Netherlands", number: 21, position: "Midfielder" , photo: "/public/photos/Dejong.JPG"},
    {name: "Kalidou Koulibaly", country: "Senegal", number: 26, position: "Defender" , photo: "/public/photos/Koulibaily.JPG"},
    {name: "Joao Felix", country: "Portugal", number: 7, position: "Forward" , photo: "/public/photos/Felix.JPG"},
    {name: "Erling Haaland", country: "Norway", number: 9, position: "Forward" , photo: "/public/photos/Halaand.JPG"},
    {name: "Ciro Immobile", country: "Italy", number: 17, position: "Forward" , photo: "/public/photos/Immobile.JPG"},
    {name: "Thomas Muller", country: "Germany", number: 25, position: "Forward" , photo: "/public/photos/Muller.JPG"},
    {name: "Jadon Sancho", country: "England", number: 7, position: "Forward" , photo: "/public/photos/Sancho.JPG"},
    {name: "Sergio Aguero", country: "Argentina", number: 10, position: "Forward" , photo: "/public/photos/Aguero.JPG"},
    {name: "Romelu Lukaku", country: "Belgium", number: 9, position: "Forward" , photo: "/public/photos/Lukaku.JPG"},
    {name: "Marcus Rashford", country: "England", number: 10, position: "Forward" , photo: "/public/photos/Rashford.JPG"},
    {name: "Luis Suarez", country: "Uruguay", number: 9, position: "Forward" , photo: "/public/photos/Suarez.JPG"},
    {name: "Wojciech Szczesny", country: "Poland", number: 1, position: "Goalkeeper" , photo: "/public/photos/Szcz.JPG"},
    {name: "Kai Havertz", country: "Germany", number: 29, position: "Forward" , photo: "/public/photos/Kai.JPG"},
    {name: "Vinicius Junior", country: "Brazil", number: 20, position: "Forward" , photo: "/public/photos/Vini.JPG"},
    // {name: "Erling Braut Haaland", country: "Norway", number: 9, position: "Forward" , photo: "/public/photos/.JPG"},
    {name: "Raphael Varane", country: "France", number: 5, position: "Defender" , photo: "/public/photos/Varane.JPG"},
    {name: "Achraf Hakimi", country: "Morocco", number: 2, position: "Defender" , photo: "/public/photos/Hakimi.JPG"},
    {name: "Nicolo Barella", country: "Italy", number: 23, position: "Midfielder" , photo: "/public/photos/Barella.JPG"},
    {name: "Lautaro Martinez", country: "Argentina", number: 10, position: "Forward" , photo: "/public/photos/Matinez.JPG"},
    {name: "Joao Cancelo", country: "Portugal", number: 27, position: "Defender" , photo: "/public/photos/Cancelo.JPG"},
    {name: "Mason Mount", country: "England", number: 19, position: "Midfielder" , photo: "/public/photos/Mount.JPG"},
    {name: "Giovanni Reyna", country: "United States", number: 32, position: "Forward" , photo: "/public/photos/Reyna.JPG"},
    {name: "Dominik Szoboszlai", country: "Hungary", number: 19, position: "Midfielder" , photo: "/public/photos/Szo.JPG"},
    {name: "Ferran Torres", country: "Spain", number: 21, position: "Forward" , photo: "/public/photos/Ferran.JPG"},
    {name: "Renato Sanches", country: "Portugal", number: 18, position: "Midfielder" , photo: "/public/photos/Renato.JPG"},
    {name: "Jules Kounde", country: "France", number: 12, position: "Defender" , photo: "/public/photos/Kounde.JPG"},
    {name: "Yusuf Demir", country: "Austria", number: 10, position: "Forward" , photo: "/public/photos/Demir.JPG"},
    {name: "Gabriel Jesus", country: "Brazil", number: 9, position: "Forward" , photo: "/public/photos/Jesus.JPG"},
    {name: "Eduardo Camavinga", country: "France", number: 18, position: "Midfielder" , photo: "/public/photos/Camavinga.JPG"},
    {name: "Serge Gnabry", country: "Germany", number: 22, position: "Forward" , photo: "/public/photos/Gnabry.JPG"},
    {name: "David Alaba", country: "Austria", number: 4, position: "Defender" , photo: "/public/photos/Alaba.JPG"},
    {name: "Raphinha", country: "Brazil", number: 18, position: "Forward", photo: "/public/photos/Raphinha.JPG"}
];